controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\Controller::homepage


# Names para el anadir
add_car_form:
    path: /add
    controller: App\Controller\Controller::addFormTwig

add_car:
    path: /add-car
    controller: App\Controller\Controller::addCar


# Names para el leer
show_cars_form:
    path: /show
    controller: App\Controller\Controller::showAllCarsTwig

show_car_by_id:
    path: /show-car
    controller: App\Controller\Controller::showProductById

show_all_cars:
    path: /show-all-cars
    controller: App\Controller\Controller::showAllCars


# Names para actualizar un producto
update_car_select:
    path: /update-select
    controller: App\Controller\Controller::selectCarToUpdateTwig

update_car_form:
    path: /update-car-form
    controller: App\Controller\Controller::sendToUpdateCarForm

update_car:
    path: /update-car
    controller: App\Controller\Controller::updateCar


# Names para eliminar un producto
delete_car_form:
    path: /delete
    controller: App\Controller\Controller::deleteFormTwig

delete_car:
    path: /delete-car
    controller: App\Controller\Controller::deleteCar


#Names para inicio de sesion y registro
sign_up_user:
    path: /sign-up
    controller: App\Controller\Controller::signUpUser

login_user:
    path: /login
    controller: App\Controller\Controller::loginUser

login_user_form:
    path: /login-form
    controller: App\Controller\Controller::showLoginAndSignUpFormTwig

close_session:
    path: /close-session
    controller: App\Controller\Controller::deleteCookie
